### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by allanj** [lawlietAi/relation-classification-via-attention-model#1]
After I clone the repo and also copy some code from the acnn repo, I still couldn't run the code actually.

**Comment by dgai91** [comment]
my code can run independently. i think maybe your pytorch version is not right

**Comment by allanj** [comment]
Hi, I use the latest pytorch version.
There are actually many small bugs, for example in acnn_train.py:
import attention.data_pro as pro
import attention.pyt_att as pa

There is no attention folder in current repo, I need to delete the attention prefix to run.

Secondly, data_pro do not have load_embedding function which I need to go back to acnn repo and copy back to this repo. And actually the arguments do no match. So I’m not sure how to run the code independently. I just stop here for now since I couldn’t find the load_embedding method. Maybe the code is not latest?

Btw, I’m wondering if the performance you reproduce match the paper

**Comment by dgai91** [comment]
I'll update data_pro. I'm sorry I'd forgot it. The performance maybe a little disappointing. Then help me point out the difference between my code and paper. thank you

**Comment by allanj** [comment]
Cool. I can also modify based on your code. Since the performance I reproduced is also not as good as in the paper. I just wonder if I did something wrong. I emailed the author and he couldn't release the code due to the license.

**Comment by dgai91** [comment]
Maybe deep learning like appearing Snape's curriculum. JUST USE THE POT TO GET FELIX FELICIS

**Comment by allanj** [comment]
So true
