### ISSUE TITLE
found two bugs that could cause your inferior performance than original paper

### ISSUE THREAD

**Issue by jind11** [lawlietAi/relation-classification-via-attention-model#2]
Hi, I have carefully read your code and found two bugs that could potentially cause your inferior performance compared with the original paper. 1. in the new_convolution function, there is missing use of self.tanh() as the activation after the convolution layer; 2. in the original paper, the convolution kernel is 1 since the input is already trigram, so there is no need to use kernel size of 3 in the new_convolution function. If you have doubt on my comments, welcome to discuss with me, thanks!

**Comment by dgai91** [comment]
ohh.i think the conv function include tanh activation. it is an interesting understanding on kernel. i think you may right. i will reconsider the kernel implementation. thanks for your discussion. keep connection

**Comment by jind11** [comment]
hi, thanks for the quick response. But I am sure the conv function at Pytorch does not include any activation function.

**Comment by dgai91** [comment]
i had read paper second time and found that kernel should be 1. cnn should not comprise activation, i searched that. could we build some new connection? you helped a lot. thank you

**Comment by jind11** [comment]
sure! my email is jindi15@mit.edu. And I also have some other revisions to your code, if you want, I can sent it to you for references.

**Comment by dgai91** [comment]
copy that. so nice to you.

**Comment by jind11** [comment]
hi, what is your email? I have some other questions for the algorithm understanding. Of if you are in US, we can have a phone call. My phone number is 617-710-6221

**Comment by dgai91** [comment]
sorry, i had sent an email to you 4 days ago. maybe my gmail can not work in the wall. oh, i am in China by the way. the policy of vpn reduce our space further.😂😂😂
my working email is dgai_ruc@aliyun.com.

**Comment by jind11** [comment]
hi, sent you an email to dgai_ruc@aliyun.com but did not get reply. my wechat is jindi930617, feel free to add me if you want

**Comment by diegoantognini** [comment]
Hi everybody,

I cannot reproduce the results at all (~25%). What were your final macro F1-score ?

Best

**Comment by dgai91** [comment]
@Diego999 hi. maybe you can replace the paper

**Comment by ShomyLiu** [comment]
@lawlietAi  hi,  I have sent you a email for the same confusion.   Looking forward to your reply

**Comment by dgai91** [comment]
@ShomyLiu thx for your discussion. i'd replied you minutes ago

**Comment by FrankWork** [comment]
Hi, any progress? What's your F1 score now?

**Comment by imnujf** [comment]
Why relation number larger than 10？To my knowledge, only 10 relations.

**Comment by TTCoding** [comment]
Hi, did you reproduce the performance declared in the original paper? I implemented it with TF, but the performance is much lower.

**Comment by jind11** [comment]
no, I can never replicate the performance in that paper. my performance is not good, around 82.7%

**Comment by charlesfufu** [comment]
> no, I can never replicate the performance in that paper. my performance is not good, around 82.7%

why my accuracy  of  model just is 25% ?

**Comment by charlesfufu** [comment]
> Hi everybody,
> 
> I cannot reproduce the results at all (~25%). What were your final macro F1-score ?
> 
> Best

Have you found the problem of accuracy with 25%?
