### ISSUE TITLE
Low Accuracy

### ISSUE THREAD

**Issue by charlesfufu** [lawlietAi/relation-classification-via-attention-model#5]
![image](https://user-images.githubusercontent.com/33311822/46591327-970b6880-caec-11e8-91d5-934dc3f5ba8d.png)
Something wrong with your program ?

**Comment by zhoudayang** [comment]
我也出现了这个问题，test_acc 最高在29，请问是怎么回事呢？

**Comment by zhoudayang** [comment]
原文中，10个epoch左右就能达到最好效果，和本实现差别很大

**Comment by dgai91** [comment]
the model of my version is an alike copy about orginal paper. last year i've tried lots of methods to improve the acc, but there is no version can be SOTA like orginal paper. so I upload the most alike version for discussion.

**Comment by charlesfufu** [comment]
> the model of my version is an alike copy about orginal paper. last year i've tried lots of methods to improve the acc, but there is no version can be SOTA like orginal paper. so I upload the most alike version for discussion.

可是29%准确率确实低了，看过你写的程序。我感觉是第一步的attention出了问题

**Comment by charlesfufu** [comment]
> the model of my version is an alike copy about orginal paper. last year i've tried lots of methods to improve the acc, but there is no version can be SOTA like orginal paper. so I upload the most alike version for discussion.

![image](https://user-images.githubusercontent.com/33311822/47080346-5a511700-d23a-11e8-9725-af86b1784fd4.png)
看到有评论说83%，不知道当初你们有交流过吗？

**Comment by dgai91** [comment]
当初交流过，不过也是去年的事了。您方便的话可以告诉我第一个att哪里有问题吗？

**Comment by dgai91** [comment]
第一个att其实没必要用软对齐

**Comment by charlesfufu** [comment]
> 当初交流过，不过也是去年的事了。您方便的话可以告诉我第一个att哪里有问题吗？

具体我也不知道细节，只是在原来PCNN的基础上加了你的第一个attention,准确率马上从原来75%降到26%左右

**Comment by charlesfufu** [comment]
> > 当初交流过，不过也是去年的事了。您方便的话可以告诉我第一个att哪里有问题吗？
> 
> 具体我也不知道细节，只是在原来PCNN的基础上加了你的第一个attention,准确率马上从原来75%降到26%左右

原作者说最后生成一个对角矩阵映射到embedding，你的第一个attention好像没有产生对角矩阵。这个点一直很迷糊。如何生成对角矩阵

**Comment by dgai91** [comment]
对角阵和数乘是一样的

**Comment by zhoudayang** [comment]
The third removes both forms of attention and additionally uses a regular objective function based on the inner product s = r · w for a sentence representation r and relation class embedding w.  不知道论文中的regular objective function是什么

**Comment by zhoudayang** [comment]
我觉得这个论文造假了，我按照论文所说的，只加了一个损失函数，发现效果大减，这个论文的损失函数明显有问题，经不过实际检验。他在论文中声明不加attention，加上损失函数能达到84.1，我加上这个损失函数，居然远远跑不过softmax。而crcnn的损失函数加上去，明显有作用。
