### ISSUE TITLE
缺少代码

### ISSUE THREAD

**Issue by zhoudayang** [lawlietAi/relation-classification-via-attention-model#6]
attention模块的代码为什么没有提交呢？ 另求此模型当前的f1值。

**Comment by dgai91** [comment]
att没有单独作为一层，是直接写在代码里的

**Comment by zhoudayang** [comment]
您好，我经过100个epoch，发现最好的test acc为34，不知道为什么？原文中经过10几个epoch就收敛了，本文是acl2016的文章，请问他实现是基于什么框架来做的呢？ 为什么离原文中的效果这么远？

**Comment by dgai91** [comment]
这个应该和框架没有关系，他的代码我并没有看到，所以我也不知道是什么情况。然后我这个代码只是把我能加的东西都加了上去，比如软对齐的att等等实际上不需要这样。

**Comment by liudonglei** [comment]
当前的repo还是无法直接运行，首先acnn_train.py的import语句需要修改、test.txt和embedding.txt等文件也未提供，大神有空能否上传一些这些文件？ @lawlietAi

**Comment by hi-wangyan** [comment]
打扰一下，请问能上传一下embeddings.txt和words.lst文件吗？谢谢你！

**Comment by dgai91** [comment]
你可以去找在我repo里提到的另一个项目，这两个文件在那个项目里

**Comment by hi-wangyan** [comment]
ok，我已经找到了，谢谢回复------------------ 原始邮件 ------------------
发件人: "Dige Ai"<notifications@github.com>
发送时间: 2019年7月14日(星期天) 下午4:17
收件人: "lawlietAi/pytorch-acnn-model"<pytorch-acnn-model@noreply.github.com>;
抄送: "wangyan"<1208554118@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [lawlietAi/pytorch-acnn-model] 缺少代码 (#6)



你可以去找在我repo里提到的另一个项目，这两个文&#x4EF6;在那个项目里
 
&mdash;
